[package]
name = "magick-sys"
version = "0.1.0"
authors = ["Petru Szemereczki | Tazz by eMAG <petru.szemereczki@tazz.ro>"]
edition = "2018"
build = "build.rs"

[dev-dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"

[features]
static = []